### PR TITLE
fixes for MacOS

### PR DESCRIPTION
**Pull request by jwoglom**
update download to store in /usr/local/bin without root
use /usr/bin/env and $HOME env variable for *nix standardization

### CODE REVIEW

**Review by Roshan-R — CHANGES_REQUESTED** [review]
First of all, thanks for the PR!

Changing from `/usr/bin/` to `/usr/local/bin` is a great idea, but it's not possible to make a file there as a normal user in linux.
image


I suggest we add sudo so it'll work on both mac and linux

**Comment by ssiyad** [comment]
Wouldn't `~/.local/share/bin` work?

**Comment by Roshan-R** [comment]
> Wouldn't `~/.local/bin` work?

Doing that would require us to add ~/.local/bin to PATH cause not every distribution does it by default. 
I'm not sure about how Mac handles it

That would mean a bigger installation command

**Comment by jwoglom** [comment]
@Roshan-R Added the sudo back

**Review by Roshan-R — APPROVED** [review]

**Comment by Roshan-R** [comment]
Thanks again for the PR @jwoglom

**Pull request merged**
