### PR TITLE
rewrite

### PR DESCRIPTION
**Pull request by odnar-dev**
- [x] Add option to update the json file (fix https://github.com/Roshan-R/termv/issues/8): `termv -u`
	- [X] using [gzip compression](https://developer.mozilla.org/en-US/docs/Glossary/GZip_compression) : save bandwidth,
image
 
	- [X] using [etag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) : check for update without downloading the whole file.
image

- [X] add option to filter by Country , Category, Language (fix https://github.com/Roshan-R/termv/issues/4)
	- [X] put filter between brackets
image
	- [X] pass arguments from terminal 
image
image

__________
- Misk
	- moved ChannelsList to "$HOME/.cache/termv/data.json"
	- errors 
image
image
	- help
image
	- use `curl`
	- check for updates every day

### CODE REVIEW

**Comment by Roshan-R** [comment]
Hey @odnar-dev thanks for the awesome work!
My apologies for responding to you this late 

The new update and download mechanism is absolutely awesome, a much much better solution than what 
I had planned to.

I like the idea of putting the filter in the text itself, it's a really neat way to handle things, but I think we could work on something to make it look a bit more intuitive
photo_2021-06-11_17-05-16
I came up with something like this, not sure about keeping categories which has null, but removing it would probably make the output cluttered, let me know what you feel

Again, absolutely awesome work!

**Comment by odnar-dev** [comment]
look nice 👍🏻 
i think you can change text 'null' with 'unsorted'

**Comment by odnar-dev** [comment]
hey @Roshan-R any news about this??

**Comment by Roshan-R** [comment]
> hey @Roshan-R any news about this??

Its a bit tricky to work on it since you are pushing this directly into the main branch, could you push this code to a new branch, this'll make it easier for me to work on it

**Comment by odnar-dev** [comment]
@Roshan-R 
ok, please create a new branch

**Comment by Roshan-R** [comment]
> @Roshan-R
> ok, please create a new branch

I've created a new branch named rewrite

**Pull request merged**
